name: Sheenam Build Pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  Build:
    runs-on: windows-2022
    steps:
    - name: Checking out Code
      uses: actions/checkout@v2
    - name: Seting Up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.200
        include-prerelease: false
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Projects
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
